import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../app/theme/app_colors.dart';
import '../../../../core/widgets/app_text_field.dart';
import '../../data/models/member_model.dart';
import '../controllers/member_controller.dart';

/// Short form to register a farmer while recording their milk. Only the
/// required details are asked for; the membership number is generated by the
/// server and the rest can be completed later in the farmer's profile.
/// Pops with the created [MemberModel].
class QuickAddFarmerDialog extends ConsumerStatefulWidget {
  /// What the collector typed in the search box, used to prefill the form.
  final String initialText;

  const QuickAddFarmerDialog({super.key, this.initialText = ''});

  static Future<MemberModel?> show(
    BuildContext context, {
    String initialText = '',
  }) {
    return showDialog<MemberModel>(
      context: context,
      builder: (_) => QuickAddFarmerDialog(initialText: initialText),
    );
  }

  @override
  ConsumerState<QuickAddFarmerDialog> createState() =>
      _QuickAddFarmerDialogState();
}

class _QuickAddFarmerDialogState extends ConsumerState<QuickAddFarmerDialog> {
  final _formKey = GlobalKey<FormState>();
  final _firstNameController = TextEditingController();
  final _lastNameController = TextEditingController();
  final _phoneController = TextEditingController();
  final _locationController = TextEditingController();

  @override
  void initState() {
    super.initState();
    final text = widget.initialText.trim();
    // A typed phone number prefills the phone; typed words prefill the names.
    if (RegExp(r'^\+?[0-9 ]{6,}$').hasMatch(text)) {
      _phoneController.text = text.replaceAll(' ', '');
    } else if (text.isNotEmpty) {
      final parts = text.split(RegExp(r'\s+'));
      _firstNameController.text = parts.first;
      _lastNameController.text = parts.skip(1).join(' ');
    }
  }

  @override
  void dispose() {
    _firstNameController.dispose();
    _lastNameController.dispose();
    _phoneController.dispose();
    _locationController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    final location = _locationController.text.trim();
    final ok = await ref
        .read(registerMemberControllerProvider.notifier)
        .registerMember(
          CreateMemberRequestModel(
            firstName: _firstNameController.text.trim(),
            lastName: _lastNameController.text.trim(),
            phone: _phoneController.text.trim(),
            location: location.isEmpty ? null : location,
          ),
        );
    if (!ok || !mounted) return;
    Navigator.of(
      context,
    ).pop(ref.read(registerMemberControllerProvider).valueOrNull);
  }

  String? _required(String? value, String field) =>
      value == null || value.trim().isEmpty ? '$field is required' : null;

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(registerMemberControllerProvider);
    final error = state.hasError
        ? state.error.toString().replaceAll('Exception: ', '')
        : null;

    return AlertDialog(
      title: const Text('Register new farmer'),
      scrollable: true,
      content: Form(
        key: _formKey,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            if (error != null) ...[
              Text(
                error,
                style: const TextStyle(color: AppColors.error, fontSize: 12),
              ),
              const SizedBox(height: 12),
            ],
            AppTextField(
              label: 'First name *',
              controller: _firstNameController,
              validator: (v) => _required(v, 'First name'),
            ),
            const SizedBox(height: 12),
            AppTextField(
              label: 'Last name *',
              controller: _lastNameController,
              validator: (v) => _required(v, 'Last name'),
            ),
            const SizedBox(height: 12),
            AppTextField(
              label: 'Phone number *',
              hint: 'e.g. 0712345678',
              controller: _phoneController,
              keyboardType: TextInputType.phone,
              validator: (v) => _required(v, 'Phone number'),
            ),
            const SizedBox(height: 12),
            AppTextField(
              label: 'Location / route (optional)',
              controller: _locationController,
            ),
            const SizedBox(height: 8),
            const Text(
              'A membership number is assigned automatically. Other details can be added later from the farmer\'s profile.',
              style: TextStyle(fontSize: 11, color: AppColors.textMuted),
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: state.isLoading ? null : () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        FilledButton(
          onPressed: state.isLoading ? null : _submit,
          child: state.isLoading
              ? const SizedBox(
                  width: 18,
                  height: 18,
                  child: CircularProgressIndicator(
                    strokeWidth: 2,
                    color: Colors.white,
                  ),
                )
              : const Text('Register'),
        ),
      ],
    );
  }
}
