-- +goose Up
-- One row per run of a background job (internal/jobs): when it ran, how it
-- was started, how it ended and what it did. Shown in the platform console;
-- rows older than 90 days are deleted by the log clean-up job.
CREATE TABLE IF NOT EXISTS job_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job VARCHAR(64) NOT NULL,
    trigger VARCHAR(16) NOT NULL,          -- START, SCHEDULE or MANUAL
    triggered_by BIGINT NULL,              -- the platform user, for MANUAL
    status VARCHAR(16) NOT NULL,           -- RUNNING, OK or FAILED
    summary TEXT NULL,                     -- what it did, e.g. "3 farmers marked inactive"
    error TEXT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP NULL
);
CREATE INDEX IF NOT EXISTS idx_job_runs_job_started ON job_runs(job, started_at DESC);

-- +goose Down
DROP TABLE IF EXISTS job_runs;
