-- Sessions: a rotated refresh token is marked replaced (not revoked) so a
-- client whose refresh response was lost on a weak connection can retry for
-- a short grace period. Reuse after that is treated as theft.
--
-- Idempotency: a write sent with an Idempotency-Key header is performed once;
-- a retry with the same key gets the stored response instead of recording the
-- sale, payment or collection again.

-- +goose Up
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS replaced_at TIMESTAMP NULL;
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires ON refresh_tokens(expires_at);

CREATE TABLE IF NOT EXISTS idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    idem_key VARCHAR(64) NOT NULL,
    method VARCHAR(10) NOT NULL,
    path VARCHAR(255) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    status_code INT NOT NULL DEFAULT 0, -- 0 while the request is running
    content_type VARCHAR(100) NULL,
    response_body TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    CONSTRAINT uq_idempotency_user_key UNIQUE (user_id, idem_key)
);

CREATE INDEX IF NOT EXISTS idx_idempotency_created ON idempotency_keys(created_at);

-- +goose Down
DROP TABLE IF EXISTS idempotency_keys;
DROP INDEX IF EXISTS idx_refresh_tokens_expires;
ALTER TABLE refresh_tokens DROP COLUMN IF EXISTS replaced_at;
